name: Links Checker

on:
  pull_request:
    paths:
      - '**.md'
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  link_checker:
    name: Check links and create automated issue if needed
    runs-on: ubuntu-latest
    env:
      REPORT_FILE: links-report
    steps:
      - uses: actions/checkout@v4

      - name: Check links in Markdown files
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          output: ${{ env.REPORT_FILE }}
          format: markdown
          fail: false
          args: >-
            --verbose
            --accept 200,204,206
            --headers "accept=text/html"
            --timeout 20
            --max-concurrency 3
            --no-progress
            --exclude-path _site
            README.md
            cs-quest/**/*.md
            fde-curriculum/**/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Report exit code
        run: echo "Lychee exited with ${{ steps.lychee.outputs.exit_code }}"

      - name: Find last open report issue
        if: github.event_name != 'pull_request'
        uses: micalevisk/last-issue-action@v2
        id: last_issue
        with:
          state: open
          labels: |
            report
            automated issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or update report issue
        if: github.event_name != 'pull_request' && steps.lychee.outputs.exit_code != '0'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link checker report
          content-filepath: ${{ env.REPORT_FILE }}
          issue-number: ${{ steps.last_issue.outputs.issue_number }}
          labels: |
            report
            automated issue

      - name: Close report issue if all links pass
        if: github.event_name != 'pull_request' && steps.lychee.outputs.exit_code == '0' && steps.last_issue.outputs.has_found == 'true'
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ steps.last_issue.outputs.issue_number }}
